### ISSUE TITLE
Option to output VTIL in text format?

### ISSUE THREAD

**Issue by VilleKrumlinde** [0xnobody/vmpattack#6]
Hi,

This tool seems very interesting, however I'm not sure what to do with the binary VTIL files it produces. Would it be possible to output the IL as readable text instead as an option? Or is there a free tool available that opens VTIL files?

**Comment by 0xnobody** [comment]
Hello,
I won't add this feature as the VTIL output files can be extremely large.
If you'd like to view the VTIL output, you can easily do so by dumping it in the console:
```cpp
vtil::routine* rtn;

std::ifstream file( "C:\\input.vtil", std::ios::binary );
vtil::deserialize( file, rtn );
vtil::debug::dump( rtn );
```
There is also a great Binary Ninja VTIL plugin that allows for exploration of VTIL routines.

**Comment by VilleKrumlinde** [comment]
Thanks but I already considered both these options.

Binary Ninja is commercial software and the free version will not run plugins as far as I can tell.

When trying to build your tool using Visual Studio 2019 I ran into trouble with the dependencies to VTIL/keystone/capstone (since building keystone requires Python runtime and Visual Studio 2013 etc. Trying to link with the released keystone.lib results in linker errors). I admit I'm no expert in building C++ projects but this got me to a dead end.

The option could be added with a warning that the output may be very large.

**Comment by 0xnobody** [comment]
I'm not gonna add the text option as that's not the purpose of VMPAttack. The purpose is to lift VMP routines for devirtualization with VTIL.

You can build it easily by first building VTIL-Core with CMake. This will automatically fetch all dependencies and build everything (including keystone/capstone) for you. Then it's as simple as changing the include/library directories in VMPAttack to the correct paths.

If you have any further questions please make a new issue.
